[package]
name = "gh-actions-local-runner"
version = "0.1.0"
authors = ["Mikail Bagishov <bagishov.mikail@yandex.ru>"]
edition = "2018"

[dependencies]
structopt = "0.2.18"
pest = "2.1.1"
pest_derive = "2.1.0"
tempfile = "3.1.0"
fs_extra = "1.1.0"
ignore = "0.4.10"
